title: Base de Continuidade (Debian2-1)
description: Cópia pública READ-ONLY — procedimentos e templates
theme: jekyll-theme-cayman
github:
  is_project_page: false

# URLs “bonitas”
permalink: pretty

# Garante que templates estáticos sejam copiados para o _site
include:
  - apache/templates/vhost-ssl.conf.tpl
  - services/templates/systemd-service.tpl
  - services/templates/env.tpl
  - services/templates/services.csv.example
