title: Base de Continuidade — Público (read-only)
description: Cópia pública READ-ONLY — procedimentos e templates
theme: jekyll-theme-cayman

# URLs bonitas: /global/01-checklist/ (sem .html)
permalink: pretty

# Publique também os templates “não-Markdown”
include:
  - apache/templates/vhost-ssl.conf.tpl
  - services/templates/systemd-service.tpl
  - services/templates/env.tpl
  - services/templates/services.csv.example

# Não enviar pastas de scripts
exclude:
  - bin
  - sync
